//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WallPoster.Assets.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WallPoster.Assets.Strings.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强调色 的本地化字符串。
        /// </summary>
        public static string Accent {
            get {
                return ResourceManager.GetString("Accent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为了您更好体验建议更换自己的KEY 的本地化字符串。
        /// </summary>
        public static string Advise {
            get {
                return ResourceManager.GetString("Advise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 和风天气KEY 的本地化字符串。
        /// </summary>
        public static string AppSecret {
            get {
                return ResourceManager.GetString("AppSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言设置 的本地化字符串。
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新 的本地化字符串。
        /// </summary>
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文简体 的本地化字符串。
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前路径 的本地化字符串。
        /// </summary>
        public static string CurrentLocation {
            get {
                return ResourceManager.GetString("CurrentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本{0} 的本地化字符串。
        /// </summary>
        public static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深色 的本地化字符串。
        /// </summary>
        public static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认显示城市 的本地化字符串。
        /// </summary>
        public static string DefaultCity {
            get {
                return ResourceManager.GetString("DefaultCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一款简单易用的本地影视收藏管理工具 的本地化字符串。
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英文 的本地化字符串。
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方向 的本地化字符串。
        /// </summary>
        public static string FlowDirection {
            get {
                return ResourceManager.GetString("FlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目开源地址 的本地化字符串。
        /// </summary>
        public static string Github {
            get {
                return ResourceManager.GetString("Github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 历史 的本地化字符串。
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂时不起作用 的本地化字符串。
        /// </summary>
        public static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浅色 的本地化字符串。
        /// </summary>
        public static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电影 的本地化字符串。
        /// </summary>
        public static string Movie {
            get {
                return ResourceManager.GetString("Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国外天气信息不完整，暂时不提供查询 的本地化字符串。
        /// </summary>
        public static string Nonsupport {
            get {
                return ResourceManager.GetString("Nonsupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导航栏设置 的本地化字符串。
        /// </summary>
        public static string PaneMode {
            get {
                return ResourceManager.GetString("PaneMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询的城市不存在或输入有误 的本地化字符串。
        /// </summary>
        public static string QueryWarning {
            get {
                return ResourceManager.GetString("QueryWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BUG反馈 的本地化字符串。
        /// </summary>
        public static string ReportBug {
            get {
                return ResourceManager.GetString("ReportBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 贡献代码 的本地化字符串。
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天气查询 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入要查询的城市 的本地化字符串。
        /// </summary>
        public static string SearchWeather {
            get {
                return ResourceManager.GetString("SearchWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电视剧 的本地化字符串。
        /// </summary>
        public static string TVplay {
            get {
                return ResourceManager.GetString("TVplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取天气信息失败,已打开错误代码页 的本地化字符串。
        /// </summary>
        public static string WeatherError {
            get {
                return ResourceManager.GetString("WeatherError", resourceCulture);
            }
        }
    }
}
